# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0cd0c9556b1f380522d4d0a34d673e590753d953461407d9b93324d275be893a40f50147382957c550dceec43f4356b9695cbf31f2a01d5cda6407fc2f6df2f2

test:
  secret_key_base: a56966028530dd32a7d520d812bd27dde021ea93bd0be4fd52caae0d924b78f2da6e3a4148efe4f51f7f6226cbf54d6a8f9a93cb9d5fca61550b576009d2e98c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
